<?php

namespace AppBundle\Repository;

/**
 * AnalyticOpenedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticOpenedRepository extends \Doctrine\ORM\EntityRepository
{
}
