<?php

namespace AppBundle\Repository;

/**
 * StatLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
